export const AGREGAR_FACTURA = 'AGREGAR_FACTURA';

export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const AUTENTICAR_USUARIO = 'AUTENTICAR_USUARIO';
export const ACTUALIZAR_USUARIO = 'ACTUALIZAR_USUARIO';
export const CAMBIAR_CLAVE_USUARIO = 'CAMBIAR_CLAVE_USUARIO';
export const NO_EXISTE_USUARIO = 'NO_EXISTE_USUARIO';